package grpc

import (
	"Nexus/internal/service"
	"Nexus/internal/state"
	pb "Nexus/proto"
	"context"
	"fmt"
	"path/filepath"
)

// NexusServer implements the interface generated by proto
type NexusServer struct {
	pb.UnimplementedNexusControllerServer
	nodeService   *service.NodeService
	fileService   *service.FileService
	lambdaService *service.LambdaService
}

// NewNexusServer creates a NexusServer with initialized NodeService, FileService, and LambdaService.
// It returns a configured *NexusServer or an error if service initialization (notably NodeService) fails.
func NewNexusServer() (*NexusServer, error) {
	// let's initialize the services in one go inside  the daemon
	ns, err := service.NewNodeService()
	if err != nil {
		return nil, err
	}
	fs := service.NewFileService()
	ls, _ := service.NewLambdaService()
	return &NexusServer{
		nodeService:   ns,
		fileService:   fs,
		lambdaService: ls,
	}, nil
}

// CreateNode
func (s *NexusServer) CreateNode(ctx context.Context, req *pb.CreateNodeRequest) (*pb.NodeResponse, error) {
	fmt.Printf("\n\n[gRPC] REQ: CreateNode name=%s mem=%d storage=%s\n", req.Name, req.MemoryMb, req.StorageSize)
	state, err := s.nodeService.CreateNode(req.Name, req.MemoryMb, uint64(req.CpuShares), req.StorageSize)
	if err != nil {
		return nil, err
	}

	return &pb.NodeResponse{
		Id:     state.ID,
		Ip:     state.IP.IP,
		Status: state.Status,
	}, nil
}

// UploadFile
func (s *NexusServer) UploadFile(ctx context.Context, req *pb.UploadFileRequest) (*pb.FileResponse, error) {
	// Here the daemon is executed as root | it must access the user's file and check that the path is absolute
	absPath, _ := filepath.Abs(req.LocalPath)
	fmt.Printf("\n\n[gRPC] REQ: UploadFile path=%s\n", absPath)
	meta, err := s.fileService.UploadFile(absPath)
	if err != nil {
		return nil, err
	}
	return &pb.FileResponse{
		Id:          meta.ID,
		Name:        meta.Name,
		Size:        meta.Size,
		ChunksCount: int32(len(meta.Chunks)),
		Status:      "Uploaded",
	}, nil
}

// ListFiles
func (s *NexusServer) ListFiles(ctx context.Context, req *pb.Empty) (*pb.FileListResponse, error) {
	files := s.fileService.ListFiles()
	var pbFiles []*pb.FileResponse
	for _, f := range files {
		pbFiles = append(pbFiles, &pb.FileResponse{
			Id:          f.ID,
			Name:        f.Name,
			Size:        f.Size,
			ChunksCount: int32(len(f.Chunks)),
		})
	}
	return &pb.FileListResponse{Files: pbFiles}, nil
}

// DownloadFile
func (s *NexusServer) DownloadFile(ctx context.Context, req *pb.DownloadFileRequest) (*pb.FileResponse, error) {
	absPath, _ := filepath.Abs(req.DestPath)
	fmt.Printf("\n\n[gRPC] REQ: DownloadFile id=%s dest=%s\n", req.FileId, absPath)

	err := s.fileService.DownloadFile(req.FileId, absPath)
	if err != nil {
		return nil, err
	}
	return &pb.FileResponse{Status: "Downloaded", Name: absPath}, nil
}

func (s *NexusServer) GetNodeMetrics(ctx context.Context, req *pb.NodeMetricsRequest) (*pb.NodeMetricsResponse, error) {
	node, exists := state.GlobalState.GetNode(req.NodeId)
	if !exists {
		return nil, fmt.Errorf("node not found")
	}

	return &pb.NodeMetricsResponse{
		NodeId:      node.ID,
		MemoryUsage: node.LatestMetrics.MemoryUsage,
		MemoryLimit: node.LatestMetrics.MemoryLimit,
		CpuPercent:  node.LatestMetrics.CPUPercent,
	}, nil
}

func (s *NexusServer) RunLambda(ctx context.Context, req *pb.LambdaRequest) (*pb.LambdaResponse, error) {
	fmt.Printf("[gRPC] REQ: RunLambda (%s)\n", req.Runtime)

	res, err := s.lambdaService.Execute(req.Code, req.Runtime)
	if err != nil {
		return nil, err
	}

	return &pb.LambdaResponse{
		Stdout:          res.Stdout,
		Stderr:          res.Stderr,
		ExitCode:        int32(res.ExitCode),
		ExecutionTimeMs: res.Duration.Milliseconds(),
	}, nil
}
