// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/nexus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NexusController_CreateNode_FullMethodName     = "/nexus.NexusController/CreateNode"
	NexusController_UploadFile_FullMethodName     = "/nexus.NexusController/UploadFile"
	NexusController_DownloadFile_FullMethodName   = "/nexus.NexusController/DownloadFile"
	NexusController_ListFiles_FullMethodName      = "/nexus.NexusController/ListFiles"
	NexusController_GetNodeMetrics_FullMethodName = "/nexus.NexusController/GetNodeMetrics"
	NexusController_RunLambda_FullMethodName      = "/nexus.NexusController/RunLambda"
)

// NexusControllerClient is the client API for NexusController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusControllerClient interface {
	// Node handling
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	// File Handling
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*FileResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*FileResponse, error)
	ListFiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FileListResponse, error)
	GetNodeMetrics(ctx context.Context, in *NodeMetricsRequest, opts ...grpc.CallOption) (*NodeMetricsResponse, error)
	RunLambda(ctx context.Context, in *LambdaRequest, opts ...grpc.CallOption) (*LambdaResponse, error)
}

type nexusControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusControllerClient(cc grpc.ClientConnInterface) NexusControllerClient {
	return &nexusControllerClient{cc}
}

func (c *nexusControllerClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, NexusController_CreateNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusControllerClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, NexusController_UploadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusControllerClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, NexusController_DownloadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusControllerClient) ListFiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FileListResponse, error) {
	out := new(FileListResponse)
	err := c.cc.Invoke(ctx, NexusController_ListFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusControllerClient) GetNodeMetrics(ctx context.Context, in *NodeMetricsRequest, opts ...grpc.CallOption) (*NodeMetricsResponse, error) {
	out := new(NodeMetricsResponse)
	err := c.cc.Invoke(ctx, NexusController_GetNodeMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusControllerClient) RunLambda(ctx context.Context, in *LambdaRequest, opts ...grpc.CallOption) (*LambdaResponse, error) {
	out := new(LambdaResponse)
	err := c.cc.Invoke(ctx, NexusController_RunLambda_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusControllerServer is the server API for NexusController service.
// All implementations must embed UnimplementedNexusControllerServer
// for forward compatibility
type NexusControllerServer interface {
	// Node handling
	CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error)
	// File Handling
	UploadFile(context.Context, *UploadFileRequest) (*FileResponse, error)
	DownloadFile(context.Context, *DownloadFileRequest) (*FileResponse, error)
	ListFiles(context.Context, *Empty) (*FileListResponse, error)
	GetNodeMetrics(context.Context, *NodeMetricsRequest) (*NodeMetricsResponse, error)
	RunLambda(context.Context, *LambdaRequest) (*LambdaResponse, error)
	mustEmbedUnimplementedNexusControllerServer()
}

// UnimplementedNexusControllerServer must be embedded to have forward compatible implementations.
type UnimplementedNexusControllerServer struct {
}

func (UnimplementedNexusControllerServer) CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedNexusControllerServer) UploadFile(context.Context, *UploadFileRequest) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedNexusControllerServer) DownloadFile(context.Context, *DownloadFileRequest) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedNexusControllerServer) ListFiles(context.Context, *Empty) (*FileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedNexusControllerServer) GetNodeMetrics(context.Context, *NodeMetricsRequest) (*NodeMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeMetrics not implemented")
}
func (UnimplementedNexusControllerServer) RunLambda(context.Context, *LambdaRequest) (*LambdaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunLambda not implemented")
}
func (UnimplementedNexusControllerServer) mustEmbedUnimplementedNexusControllerServer() {}

// UnsafeNexusControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusControllerServer will
// result in compilation errors.
type UnsafeNexusControllerServer interface {
	mustEmbedUnimplementedNexusControllerServer()
}

func RegisterNexusControllerServer(s grpc.ServiceRegistrar, srv NexusControllerServer) {
	s.RegisterService(&NexusController_ServiceDesc, srv)
}

func _NexusController_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusController_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusController_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusController_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).ListFiles(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusController_GetNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).GetNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_GetNodeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).GetNodeMetrics(ctx, req.(*NodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusController_RunLambda_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LambdaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusControllerServer).RunLambda(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusController_RunLambda_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusControllerServer).RunLambda(ctx, req.(*LambdaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusController_ServiceDesc is the grpc.ServiceDesc for NexusController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.NexusController",
	HandlerType: (*NexusControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _NexusController_CreateNode_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _NexusController_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _NexusController_DownloadFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _NexusController_ListFiles_Handler,
		},
		{
			MethodName: "GetNodeMetrics",
			Handler:    _NexusController_GetNodeMetrics_Handler,
		},
		{
			MethodName: "RunLambda",
			Handler:    _NexusController_RunLambda_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nexus.proto",
}
